version: "3.1"

services:
  bagisto-php-apache:
    build:
      args:
        uid: 1000
        user: $USER
        container_project_path: /var/www/html/
      context: .
      dockerfile: ./Dockerfile
    image: bagisto-php-apache
    ports:
      - 8081:80
    volumes:
      - ./workspace/:/var/www/html/
    labels:
      - traefik.http.services.bagisto-php-apache.loadbalancer.server.port=8081

  bagisto-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Randomized external port (host-side)
    volumes:
      - mysql-data:/var/lib/mysql/


volumes:
  mysql-data:
